### ISSUE TITLE
User can search for recipes with a search term

### ISSUE THREAD

**Issue by junoulee** [junoulee/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for recipes with a search term.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have access to hundreds of recipes through a simple search.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/211622822-120ba166-30d6-44e5-bb2d-064d6b7699cf.png)
![image](https://user-images.githubusercontent.com/117887912/211622912-f8dfe2d0-344f-4d27-b8ad-d5252a23bc58.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the page where the user can search in the data-view="search-view" element. This page needs to match the format shown in the example figma.
- [x] Complete the HTML form using the appropriate responsive layout classes.
    - [x] Write CSS for mobile devices first.
    - [x] Adjust styling to fluidly adapt to desktop.
- [x] In `main.js`, define functions to retrieve data from API when user enters a keyword in the search bar.
    - [x] Confirm that both `enter` as well as clicking on the search button send 'GET' requests.
    - [x] Confirm that blank entries do not get submitted.
- [x] Create a data model in `data.js`
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
