### ISSUE TITLE
User can view a list of search results

### ISSUE THREAD

**Issue by junoulee** [junoulee/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of search results.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can browse through recipes they have searched.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/211624928-66b6e18b-5ce4-448b-b0fd-2b3b3ddaa247.png)
![image](https://user-images.githubusercontent.com/117887912/211625026-bd28a903-74dc-41eb-82d7-aabb8cf151ef.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an empty unordered list to a new `row` element in the HTML.
- [x] Create some dummy recipe results to the unordered list in the HTML and style them to match the example results in the figma. Each result's content should be in a single `li` element within the `ul` element.
- [x] Check that the example results that were just created in the unordered list are responsive for both mobile and desktop screens.
- [x] Define a function named `renderResult` with a single parameter named `result`. This parameter represents a single object for matching results from the `xhr.response` object. The function should generate and return a DOM tree for each result that matches the dummy results created in the unordered list.
  - [x] Create an event listener on the `document` which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the `xhr.response` object and generate a DOM tree for each recipe in the object, and append that DOM tree to the unordered list.
  - [x]  Remove the example HTML results from `index.html` once the user's results are successfully being appended to the DOM on page load.
      - [x] If results are properly being displayed after a search, clear displayed results when user submits a new search.
      - [x] Display text for matching results above the recipe cards.
      - [x] Display text for no matches found.
  - [x] Update the `search` callback for the search bar to do the following:
      - [x] Render a DOM tree for the matching result object using the `renderResult` function.
      - [x] Prepends the new DOM tree to the unordered list.
  - [x] Clean up all unnecessary styling.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Test the app some more in a private browsing tab.
  - [x] Fix all errors.
