### ISSUE TITLE
User can view the details for a single recipe

### ISSUE THREAD

**Issue by junoulee** [junoulee/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details for a single recipe.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on recipes to view details as well as visit the recipe page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/211626101-e894f04e-ea47-4a9a-a78f-83e8626e609b.png)
![image](https://user-images.githubusercontent.com/117887912/211626170-b468af0d-64ec-41c5-8667-a313e908f5f9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In `data.js`, add an array along with an ID to store search results inside the data model.
    - [x] Set an attribute of a matching ID for each search result on the `li` DOM tree.
    - [x] Clear out the data model array if user submits a new search.
    - [x] Reset result ID if user submits a new search. 
- [x] Add a `click` event listener to each recipe card.
    - [x] Ensure that all locations of recipe respond to clicks.
    - [x] Each element of recipe card should display `cursor: pointer` when hovered with the mouse.
- [x] Design a modal that displays recipe details when user clicks on a recipe card.
    - [x] Create a dummy modal in the HTML.
    - [x] Add an X icon on each recipe card.
    - [x] Write CSS for mobile devices first.
    - [x] Adjust styling to fluidly adapt to desktop.
- [x] Design a `button` on the modal that directs user to recipe site.
    - [x] Direct the user to the original recipe site in a new tab.
- [x] Define a function to render recipe details to be appended to the DOM when user clicks on a recipe card.
- [x] Allow user to close the modal to return to the results page.
    - [x] Add a `click` event listener to each X button.
    - [x] Allow user to click on another recipe to display a different modal.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
