### ISSUE TITLE
User can save recipe to their favorites

### ISSUE THREAD

**Issue by junoulee** [junoulee/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save recipe to their favorites.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can click "like" on a recipe to save in their recipe collection for future reference.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/211626723-fc245444-e650-41be-ada7-e5c7ad03c037.png)
![image](https://user-images.githubusercontent.com/117887912/211626816-292c2c26-a8d3-4d11-b57a-d508fbfdf028.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add heart icon along with the string "add to favorites" on the modal on the HTML.
    - [x] Update the `renderModal` function to render the heart icon as well as "add to favorites" text on each modal.
    - [x] Add event listeners to the icon as well as the text on the modal. 
- [x] In `main.js` define a function named `addToFavorites` that will act as the callback function for the `click` event for the icon as well as the text. 
    - [x] This function should push the selected recipe to the `favorites` array in `data.js`. 
    - [x] Once pushed into the `favorites` array, favorited recipes should also be assigned a `favoritesId`.
- [x] In `data.js` , add a `beforeunload` event listener to the `window` object that serializes the `favorites` array as JSON and stores the JSON in `localStorage`.
- [x] At the bottom of `data.js`, include a conditional statement that:
    - [x] checks to see if there is a JSON data array stored in `localStorage`.
    - [x] if there is, parse it and assign it to the `favorites` variable so that the user can continue adding recipes to the pre-existing favorites list.
- [x] Test the app by liking some recipes and then reloading the page to confirm that: 
    - [x] the favorites array is being saved to `localStorage` before each page reload.
    - [x] each new liked recipe is receiving an incrementing `favoritesId` property.
- [x] When a user clicks saves a recipe to favorites, change the heart icon color to red and change text to read "added to favorites".
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
