### ISSUE TITLE
User can view their favorites list

### ISSUE THREAD

**Issue by junoulee** [junoulee/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their favorites list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can view and browse through the recipes they have saved.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/211627266-a701b8e9-6984-466a-8ae4-ee8bf0cdcb64.png)
![image](https://user-images.githubusercontent.com/117887912/211627415-b8c6484a-e808-4443-9d5b-34aa9309a501.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an anchor to the navbar to show the ”`favorites`” view. 
    - [x] Assign `click` event listeners to both links on the nav bar.
    - [x] Define a `viewSwap` function that toggles between "`search`" view and "`favorites`" view when user clicks on relevant links on the nav bar.
- [x] Design "`favorites`" view page by using HTML and CSS.
    - [x] Add heart icons on each recipe card to display that the recipe has been favorited.
    - [x]  Write CSS for mobile devices first.
    - [x]  Adjust styling to fluidly adapt to desktop.
- [x] Create an event listener on the `document` which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the `data.favorites` array and generate a DOM tree for each entry in the array, and append that DOM tree to display favorited recipe cards.
    - [x] Add `click` event listeners on each recipe card for the user to view.
    - [x] If clicked, render a modal to display recipe details.
- [x] Define function `removeFavorites` that removes the favorited recipe from the favorites page.
    - [x]  Define function `faveModalClose` that re-renders the favorited recipes to account for removed favorites when the user clicks `x`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Remove all console logs and commented out code.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
